# num=int(input('Enter the eight number'))
num=set()
num.add(input("enter the 1st number"))
num.add(input("enter the 2nd number"))
num.add(input("enter the 3rd number"))
num.add(input("enter the 4rth number"))
num.add(input("enter the 5th number"))
num.add(input("enter the 6th number"))
num.add(input("enter the 7th number"))
num.add(input("enter the 8 number"))
print(num)