list=[1,6,21,4,64,10,243,123]
print("This function is use to reverse the list")
list.reverse()
print(list)
print("This function is use to Sort the list")
list.sort()
print(list)
print("This function is use to insert element at the end of  the list")
list.append(999)
print(list)
print("This function is use to insert element on the followed index of the list")
list.insert(4,396)
print(list)
print("This function is use to delete element on the followed index of the list")
list.pop(2)
print(list)
print("This function is use to remove the element on the followed index of the list")
list.remove(396)
print(list)